main:
    resource: "@MainBundle/Controller/MainController.php"
    prefix:   /
    type: annotation

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"