main:
    resource: "@MainBundle/Controller/MainController.php"
    prefix:   /
    type: annotation

visao_i:
    resource: "@VisaoIBundle/Controller/VisaoIController.php"
    prefix:   /
    type: annotation

tarefas:
    resource: "@VisaoIBundle/Controller/TarefasController.php"
    prefix:   /
    type: annotation

notas:
    resource: "@VisaoIBundle/Controller/NotasController.php"
    prefix:   /
    type: annotation

provas:
    resource: "@VisaoIBundle/Controller/ProvasController.php"
    prefix:   /
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"